name: 🌊 INTERNET CONNECT AUTO

on:
  workflow_dispatch:
  push:
    paths:
      - 'Internet-Connect-Auto/**'

jobs:
  autonomous-ocean-pulse:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Bắt buộc để Workflow có quyền tự viết log vào kho
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Launch system
        run: python "Internet-Connect-Auto/Internet-Connect-Auto.py"
      - name: Commit and Push Log
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Connection-Log.txt
          git commit -m "Auto: Update connection log" || echo "No changes to commit"
          git push
